language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=2.0.1
    - ES_VERSION=2.1.2
    - ES_VERSION=2.2.0

install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false
  - pip install git+https://github.com/elastic/elasticsearch-py.git#egg=elasticsearch
  - pip install .

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - honza.kral@gmail.com
